-- minimized main.lua + object.lua
-------------------------------------------------------------------------------

timer_corpse=20timer_target=24timer_seen_player=5timer_dialog_line=24timer_effect=16timer_effect_poison=6timer_spell=24timer_spell_charm=48max_followers=5state_reset="reset"state_title="title"state_game="game"state_menu="menu"state_look="look"state_dialogue="dialogue"state_chest="chest"state_read="read"state_game_over="game_over"status_charmed=1status_scared=2status_sleeping=4status_poisoned=8statuses=split"0b0001,0b0010,0b0100,0b1000"flag_collision=0flag_block_view=1flag_entity=2state=nil room=nil turn=1frame=0prev_frame=0 blink_frame=0 blink=false flash_frame=0fade_frame=0fade_chars=split"░,▒"fade_action=nil pal_lock=false cam_x=0cam_y=0cam_offset=4cam_x_min=0cam_y_min=0cam_x_diff=0cam_y_diff=0title_effect_num=96title_effect_colors=split"8,9,10,11,12,13,14,15"title_text=split(data_story_intro,"\n")spells=split"befriend,scare,sleep,poison"spell_cd=split"0,0,0,0"spells_desc=split"???\n???\n???\n???,???\n???\n???\n???,???\n???\n???\n???,???\n???\n???\n???"tomes=0max_tomes=4keys=split"0,0,0"key_names=split"iron key,gold key,green key"consumables=split"0"consumable_names=split"potion"consumable_values=split"15"function _init()change_state(state_title)populate_map()end function _update()if(state==state_reset)run()else blink_frame=(blink_frame+1)%2blink=blink_frame%2==0prev_frame=frame frame=flr(t()*2%2)update[state]()
end function _draw()if(state~=state_reset)draw[state]()draw.flash_step()draw.fade_step()
end init={title=function(n)title_idle=true title_pos=0end,menu=function(n)sel_menu={tab=0,i=1}end,look=function(n)sel_look={spell=0,x=player.x,y=player.y}set_look()end,dialogue=function(n)sel_dialogue=n end,chest=function(n)sel_chest=n end,read=function(n)sel_read=n end}update={title=function()if(not title_idle)title_pos+=.2
if(title_pos>=str_height(data_story_intro)*8+85and fade_frame==0)draw.play_fade(change_state,state_game)
input.title()end,game=function()for n in all(entity.entities)do n:update()end update_camera()if(not creature.anim_playing and input.game())do_turn()
end,menu=function()input.menu()end,look=function()if(input.look())set_look()
end,dialogue=function()input.dialogue()end,chest=function()if(sel_chest.entity.anim_this)sel_chest.entity:anim_step()
input.chest()end,read=function()input.read()end,game_over=function()for n in all(entity.entities)do n:update()end input.game_over()end}draw={play_fade=function(n,e)fade_frame=5fade_action=n and{func=n,param=e}or nil end,fade_step=function()if fade_frame>0do if(fade_frame==3)rectfill(0,0,128,128,0)else for n=0,15do for e=0,15do print("ᵉ"..fade_chars[fade_frame>#fade_chars and 6-fade_frame or fade_frame],n*8,e*8,0)end end
fade_frame-=1if(fade_frame==3and fade_action)fade_action.func(fade_action.param)
end end,flash_step=function()if(flash_frame>0)cls(state==state_game and player.hp<5and flash_frame==1and 8or 7)flash_frame-=1
end,monochrome=function()poke(24404,96)pal_all(1)sspr(0,0,128,128,0,0)pal_set()poke(24404,0)end,window_frame=function(n)n=n or 2if(n>0)rectfill(0,125-n*7,127,127,1)line(0,125-n*7,127,125-n*7,6)
rect(0,0,127,127,6)pset(0,0,0)pset(127,0,0)pset(0,127,0)pset(127,127,0)end,title=function()cls(0)camera(0,title_pos)for n=1,title_effect_num do local e,o,d=cos(t()/8+n/title_effect_num)*56,sin(t()/8+n/title_effect_num)*16+sin(t()+n*(1/title_effect_num)*5)*4,title_effect_colors[n%#title_effect_colors+1]for n=1,3do pset(62+e+n,50+o+n,d)end end s_print("ᵉmagus magicus",13,45,true,true,7,4)print("ˇˇˇˇˇˇˇˇˇˇˇˇ",19,54,6)if not title_idle do for e,n in pairs(title_text)do print(n,64-str_width(n)*.5,78+e*8,5)print(n,64-str_width(n)*.5,77+e*8,6)end elseif frame==0do s_print("start game ❎",38,85)end camera(0,0)for n=0,1do for e=0,15do local e=e*8+flr(rnd()+.5)print("ᵉ"..fade_chars[2],e,130*n-5,0)print("ᵉ"..fade_chars[1],e,128*n-4,0)end end draw.window_frame(0)clip(1,84,126,43)end,game=function()cls()if room do local n,e,o,d=max(0,(room[2]-cam_x+1)*8),max(0,(room[3]-cam_y+1)*8),min(128,(room[4]-cam_x)*8),min(128,(room[5]-cam_y)*8)if(room[1]>0)pal_all(1,true)map(cam_x-cam_x_diff-1,cam_y-cam_y_diff-room[1]-1,-8,-8,18,16)for n in all(entity.entities)do n:draw({x=cam_x_diff,y=cam_y_diff+room[1]})end pal_unlock()
rectfill(n,e,o,d,0)map(room[2],room[3],(room[2]-cam_x)*8,(room[3]-cam_y)*8,room[4]-room[2]+1,room[5]-room[3]+1)clip(n,e,o-n,d-e)else map(cam_x-1,cam_y-1,-8,-8,18,16)end for n in all(entity.entities)do if(n~=player and(n.parent_class~=creature.class or n.dead))n:draw()end for n in all(entity.entities)do if(n~=player and(n.parent_class==creature.class and not n.dead))n:draw()end player:draw()clip()camera()draw.window_frame()local n=max(0,player.hp/player.max_hp)s_print("hp:",2,120,state==state_game)if(state==state_game)rectfill(14,120,82,124,5)
if(n>0)rectfill(14,120,14+68*n,124,n<.25and 8or n<.5and 9or n<.75and 10or 11)
s_print("menu 🅾️",98,113,state==state_game)s_print("look ❎",98,120,state==state_game)clip(0,0,msg.frame,128)if(state==state_game)print(msg.txt,2,114,5)
print(msg.txt,2,113,6)clip(msg.frame,0,msg.frame>msg.width-3and msg.width-msg.frame or 3,128)print(msg.txt,2,112,7)clip()if(state==state_game or state==state_game_over)msg.anim_step()
end,menu=function()draw.game()draw.monochrome()line(32,21,94,21,6)line(32,90,94,90,6)line(31,22,31,89,6)line(95,22,95,89,6)rectfill(32,21,94,27,6)line(32,59,94,59,6)local n="cancel 🅾️  use ❎"print(n,30,99,5)clip(30,0,(sel_menu.tab==0and spell_cd[sel_menu.i]==0or sel_menu.tab==1and tbl_sum(consumables)>0)and 80or 40,128)print(n,30,98,6)clip()if sel_menu.tab==0do print("⬅️ magick ➡️",40,22,0)print("▶",34,24+sel_menu.i*7,6)for n=1,tbl_len(spells)do local e,o=spell_cd[n]>0and"("..spell_cd[n]..") "or n==1and#player.followers>=max_followers and"(max) "or"",24+n*7print(e..spells[n],39,o,sel_menu.i==n and spell_cd[n]==0and 6or 5)if(spell_cd[n]>0)line(37+str_width(e),o+1,39+str_width(e)+str_width(spells[n]),o+3,5)
end local n=split(spells_desc[sel_menu.i],"\n")for e=1,tbl_len(n)do print(n[e],34,55+e*7,6)end elseif sel_menu.tab==1do print("⬅️ inventory ➡️",34,22,0)if tbl_sum(consumables)==0do print("nothing",36,31,5)else print("▶",34,24+sel_menu.i*7,6)for n=1,#consumables do if(consumables[n]>0)print((consumables[n]>1and"("..consumables[n]..") "or"")..consumable_names[n],39,24+n*7,sel_menu.i==n and 6or 5)end end print("tomes:      "..tomes.."/"..max_tomes,34,62,6)print(key_names[1].."s:    "..keys[1],34,69,6)print(key_names[2].."s:    "..keys[2],34,76,6)print(key_names[3].."s:   "..keys[3],34,83,6)end end,look=function()draw.game()if(state==state_look)draw.monochrome()
player:draw()if(sel_look.entity)sel_look.entity:draw()
if(state==state_look)vec2_spr(14,pos_to_screen(sel_look))
draw.window_frame()local n=sel_look.text.." ❎"s_print(sel_look.spell==0and"target:"or"cast "..spells[sel_look.spell].." on:",2,113,state==state_look)s_print(sel_look.name,2,120,state==state_look,sel_look.entity~=nil,sel_look.color,sel_look.entity and sel_look.entity.parent_class==creature.class and 0or 5)s_print("cancel 🅾️",90,113,state==state_look)s_print(n,126-str_width(n),120,state==state_look,sel_look.usable)end,dialogue=function()draw.game()draw.monochrome()player:draw()sel_dialogue.entity:draw()draw.window_frame(4)if(sel_dialogue.anim_frame[min(sel_dialogue.pos+2,#sel_dialogue.text)]<=0and frame==0)s_print("continue ❎",82,99)
s_print(sel_dialogue.entity:get_name()..":",2,99)for n,e in pairs(sel_dialogue.text)do local o=sel_dialogue.anim_frame[n]if n>=sel_dialogue.pos and n<=sel_dialogue.pos+2do local d=106+(n-sel_dialogue.pos)*7clip(0,0,#e*4+timer_dialog_line-o,128)s_print(e,2,d)if(o>0and o~=#e*4+timer_dialog_line)clip(#e*4+timer_dialog_line-o,0,3,128)print(e,2,d-1,7)
if(o>0and(n==sel_dialogue.pos or sel_dialogue.anim_frame[n-1]<=0))sel_dialogue.anim_frame[n]-=3
end end clip()end,chest=function()local e=sel_chest.entity local o=tbl_len(e.content)cls()player:draw()e:draw()if(not chest.anim_playing)draw.monochrome()
if e.anim_frame<=0do for n=1,o do local d,f=sel_chest.anim_frame[n],{x=52-o*8+n*16,y=52}if n==1or sel_chest.anim_frame[n-1]<=0do local t=e.content[n]if d>0do if(n==o)e.anim_this=false
pal_all(7)for n=0,10do local n=e:item_anim_pos(smoothstep(min(1,1-d/60+.025*n)),f)if(blink)vec2_spr(t.sprite,n)
end pal_set()sel_chest.anim_frame[n]-=1if(sel_chest.anim_frame[o]<=0)chest.anim_playing=false flash_frame=2
elseif not chest.anim_playing or blink do vec2_spr(t.sprite,vec2_add(f,{x=0,y=wavy()}))end end end end if(not chest.anim_playing)wavy_print("take items ❎",38,85)
end,read=function()draw.look()draw.monochrome()local n=split(sel_read.message,"\n")local e=max(#n-5,0)*4local o,d=34-e,76+e rectfill(23,o,103,d,sel_read.bg)line(24,o-1,102,o-1,sel_read.bg)line(24,d+1,102,d+1,sel_read.bg)for o=1,tbl_len(n)do print(n[o],64-str_width(n[o])*.5,29-e+max(5-#n,0)*4+o*8,sel_read.fg)end s_print("continue ❎",42,85+e)end,game_over=function()draw.game()draw.monochrome()if(tomes==max_tomes)local n=split"you won!,congratulations!"for o=1,#n do local e=n[o]for n=1,#e do s_print(sub(e,n,n),64-#e*3+(n-1)*6,o*12+32+n*1.5+wavy(n,3),true,true,10,13)end end else wavy_print("g a m e   o v e r",26,55,8,1)if(frame==0)s_print("restart ❎",44,85)
end}input={title=function()if(btnp(5))if(title_idle)draw.play_fade(toggle_bool,"title_idle")else draw.play_fade(change_state,state_game)
end,game=function()local n,e,o=false,player.x,player.y if btn(0)do n=player:action_dir(e-1,o)elseif btn(1)do n=player:action_dir(e+1,o)elseif btn(2)do n=player:action_dir(e,o-1)elseif btn(3)do n=player:action_dir(e,o+1)elseif btnp(4)do change_state(state_menu)elseif btnp(5)do change_state(state_look)end return n end,menu=function()if btnp(0)do sel_menu.i=1sel_menu.tab=(sel_menu.tab-1)%2elseif btnp(1)do sel_menu.i=1sel_menu.tab=(sel_menu.tab+1)%2elseif btnp(2)and sel_menu.i>1do sel_menu.i-=1elseif btnp(4)do change_state(state_game)elseif sel_menu.tab==0do if btnp(3)and sel_menu.i<tbl_len(spells)do sel_menu.i+=1elseif btnp(5)and spell_cd[sel_menu.i]==0do change_state(state_look)sel_look.spell=sel_menu.i set_look()end elseif sel_menu.tab==1do if btnp(3)and sel_menu.i<tbl_len_nonzero(consumables)do sel_menu.i+=1elseif btnp(5)and tbl_sum(consumables)>0do local n=sel_menu.i for e=1,tbl_len(consumables)do if(consumables[e]>0)n-=1
if(n==0)n=e break
end msg.add("consumed "..consumable_names[n])player:take_dmg(-consumable_values[n])consumables[n]-=1change_state(state_game)end end end,look=function()if btnp(0)and sel_look.x-cam_x>0do sel_look.x-=1elseif btnp(1)and sel_look.x-cam_x<15do sel_look.x+=1elseif btnp(2)and sel_look.y-cam_y>0do sel_look.y-=1elseif btnp(3)and sel_look.y-cam_y<13do sel_look.y+=1elseif btnp(4)do change_state(state_game)return false elseif btnp(5)and sel_look.spell==0and sel_look.usable do sel_look.entity:interact()if(sel_look.key>0)keys[sel_look.key]-=1
return false elseif btnp(5)and sel_look.spell>0and sel_look.usable do change_state(state_game)cast_spell(sel_look.spell,sel_look.entity)do_turn()spell_cd[sel_look.spell]=sel_look.spell==1and timer_spell_charm or timer_spell return false end return true end,dialogue=function()if(btnp(5))if(sel_dialogue.pos+2<#sel_dialogue.text)sel_dialogue.pos+=3else change_state(state_game)
end,chest=function()if(btnp(5))sel_chest.entity.anim_frame=0if chest.anim_playing do for n=1,tbl_len(sel_chest.anim_frame)do sel_chest.anim_frame[n]=1end elseif tomes==max_tomes do change_state(state_game_over)else change_state(state_game)end
end,read=function()if(btnp(5))change_state(state_game)
end,game_over=function()if(btnp(5)and tomes~=max_tomes)reset()
end}msg={width=94,queue={},txt="welcome to game",turn=0,frame=0,delay=0,add=function(n)if(msg.turn<turn)msg.queue={}msg.turn=turn msg.txt_set(n)else add(msg.queue,n)
end,txt_set=function(n)msg.txt=n msg.frame=0msg.delay=8end,anim_step=function()if msg.frame>=msg.width do msg.frame=msg.width if(#msg.queue>0)msg.delay-=1if(msg.delay<=0)msg.txt_set(deli(msg.queue,1))
else msg.frame+=3end end}function reset()change_state(state_reset)for n=0,32767,rnd(15)do poke(n,rnd(15))end end function change_state(n,e)state=n if(init[state])init[state](e)
end function pos_to_screen(n)return{x=8*(n.x-cam_x),y=8*(n.y-cam_y)}end function pal_set(n,e)if(not pal_lock)pal_lock=e or false pal(n)
end function pal_all(n,e)pal_set({0,n,n,n,n,n,n,n,n,n,n,n,n,n,n},e or false)end function pal_unlock()pal_lock=false pal()end function populate_map()for n=0,127do for e=0,67do if(fget(mget(n,e),flag_entity))entity.entity_spawn(mget(n,e),n,e)
if(mget(n,e)==0)mset(n,e,1)
end end end function collision(n,e)if(n<0or n==103or n==128or e<0or e==64or fget(mget(n,e),flag_collision))return true
for o in all(entity.entities)do if(o.collision and o.x==n and o.y==e)return true end return false end function in_reach(n,e)return dist(n,e)<=1and(n.x==e.x or n.y==e.y or not collision(n.x,e.y)or not collision(e.x,n.y))end function do_turn()for n=1,tbl_len(spells)do spell_cd[n]=max(0,spell_cd[n]-1)end for n in all(entity.entities)do n:do_turn()end turn+=1end function update_camera()local n,e,o,d=cam_x,cam_y,player.x,player.y if(o-cam_x>15-cam_offset and(room or cam_x<87))n=o-15+cam_offset
if(o-cam_x<cam_offset and cam_x>cam_x_min)n=o-cam_offset
if(d-cam_y>13-cam_offset and cam_y<50)e=d-13+cam_offset
if(d-cam_y<cam_offset and cam_y>cam_y_min)e=d-cam_offset
if(room==nil and cam_x<cam_x_min)n=cam_x_min
if(room==nil and cam_y<cam_y_min)e=cam_y_min
if(n~=cam_x or e~=cam_y)if(player.anim_frame>0)camera((n-cam_x)*8+player.anim_x,(e-cam_y)*8+player.anim_y)else cam_x,cam_y=n,e
end function change_room(n)room=n end function cast_spell(n,e)msg.add("casted "..spells[n])status=statuses[n]e:add_status(status)if(status==status_charmed and#player.followers>max_followers)for n in all(player.followers)do n:clear_status(status_charmed)break end
end function in_sight(n,e)local e,o=e.x-n.x,e.y-n.y local t=abs(e)>=abs(o)and abs(e)or abs(o)e,o=e/t,o/t local d,f,a,r,i,l=n.x,n.y,n.x,n.y,false,false for t=1,t+1do i=fget(mget(d,r),flag_block_view)and fget(mget(a,f),flag_block_view)or fget(mget(d,f),flag_block_view)or l if(i)return false
l,a,r,d,f=i,d,f,n.x+flr(e*t+.5),n.y+flr(o*t+.5)t+=1end return true end function add_to_inventory(n)local e,n=n.type,n.value if(e==1)tomes+=1return"tome"
if(e==2)keys[n]+=1return key_names[n]
if(e==3)consumables[n]+=1return consumable_names[n]
end function set_look()tbl_merge(sel_look,{name="none",usable=false,text="interact",color=5,key=0})sel_look.entity=nil local n=entity.entity_at(sel_look.x,sel_look.y)if(n and sel_look.spell>0)n=n.class==enemy.class and not n.dead and not n:check_status(status_charmed)and n or nil
if(n)n:look_at(sel_look)if(sel_look.spell>0)sel_look.usable=in_sight(player,sel_look)
if(sel_look.spell>0)sel_look.text="cast"
end object={class="object",parent_class=nil,inherit=function(n,e)return setmetatable(e or{},{__index=n})end}drawable=object:inherit({class="drawable",parent_class=object.class,sprite=0,flipped=false,flash_frame=0,vec2_spr=function(n,e,o)local o=o or n.sprite n:spr(e.x,e.y,o)end,spr=function(n,e,o,d)local d=d or n.sprite if(n.flash_frame>0)n.flash_frame-=1pal_all(7)
palt(0,false)palt(15,true)spr(d,e,o,1,1,n.flipped)pal_set()end})entity=drawable:inherit({class="entity",parent_class=drawable.class,entities={},num=0,x=0,y=0,name=nil,collision=true,interactable=true,interact_text="interact",turn=0,entity_at=function(e,o)for n in all(entity.entities)do if(n.class==item.class and n.x==e and n.y==o)return n end for n in all(entity.entities)do if(n.class==enemy.class and n.x==e and n.y==o and not n:check_status(status_charmed)and not n.dead)return n end for n in all(entity.entities)do if(n.x==e and n.y==o)return n end return nil end,entity_spawn=function(d,e,o)mset(e,o,1)local n,d={x=e,y=o,sprite=d},data_entities[d]if(d)if(d.class==player.class)tbl_merge(player,n)local n=rnd()>.5and 17or 18tbl_merge(companion,tbl_merge_new({x=e,y=o,sprite=n},data_entities[n]))else tbl_merge(n,d)_𝘦𝘯𝘷[n.class]:new(n)
end,new=function(n,e)local n=n:inherit(e)entity.num=entity.num+1n["id"]=entity.num n["prev_x"],n["prev_y"]=n.x,n.y add(entity.entities,n)return n end,destroy=function(n)del(entity.entities,n)end,update=function(n)end,draw=function(n,e,o,d)if(n:in_frame(e))n:vec2_spr(vec2_add(o or pos_to_screen(n),vec2_scale(e or{x=0,y=0},8)),d)return true
return false end,get_name=function(n)return n.name and n.name or n.item_class and n.item_class or n.class end,look_at=function(n,e)tbl_merge(e,{entity=n,name=n:get_name(),color=6,text=n.interact_text,usable=n.interactable and in_reach(player,n)})end,interact=function(n)end,do_turn=function(n)end,in_frame=function(n,e)local n=vec2_add(n,e or{x=0,y=0})return n.x>=cam_x-1and n.x<cam_x+17and n.y>=cam_y-1and n.y<cam_y+15end})creature=entity:inherit({class="creature",parent_class=entity.class,anims={move=split"4,8",attack=split"5,6"},anim_queue={},anim_playing=false,dead=false,attacked=false,blink_delay=0,anim=nil,anim_frame=0,anim_x=0,anim_y=0,anim_x1=0,anim_y1=0,dhp=0,dhp_turn=0,target=nil,target_turn=0,status=0,status_timer={},followed=false,max_hp=10,ap=2,new=function(n,e)local n=entity.new(n,e)n["hp"]=n.max_hp return n end,update=function(n)if n.anim_frame>0do for e in all(creature.anim_queue)do if(e==n)n:anim_step()
if(e.anim==creature.anims.attack)break
end elseif prev_frame~=frame and n.blink_delay>0do n.blink_delay-=1end end,draw=function(n,o)if n:in_frame(o)do local e,d,f=n.sprite+frame*16,n:screen_pos().x,n:screen_pos().y if n.anim_frame<=0do if n.dead do e=frame==1and turn-n.dhp_turn<=1and n.blink_delay<=0and not creature.anim_playing and 0or 3elseif n.attacked and frame==1and n.blink_delay<=0and not creature.anim_playing do e=0if(state==state_game)print(abs(n.dhp),d+4-str_width(abs(n.dhp))*.5,f+1,n.dhp<0and 8or 11)
end end entity.draw(n,o,n:screen_pos(),e)if e~=0and e~=3do local e={x=d,y=f}if(n:check_status(status_charmed))vec2_spr(15,e)e.x+=6
if(n:check_status(status_sleeping))vec2_spr(47,e)e.x+=4
if(n:check_status(status_scared))vec2_spr(31,e)e.x+=3
if(n:check_status(status_poisoned))vec2_spr(63,e)e.x+=4
end return true end return false end,screen_pos=function(n)return vec2_add(pos_to_screen(n),{x=n.anim_x,y=n.anim_y})end,look_at=function(n,e)if(not n.dead)entity.look_at(n,e)e.color=n.class==enemy.class and not n:check_status(status_charmed)and 2or 3return true
return false end,do_turn=function(n)if(turn>n.dhp_turn)n.attacked=false
if(n.dead and turn-n.dhp_turn>timer_corpse)n:destroy()
if(n.target and(n.target.dead or turn>n.target_turn+timer_target or n.target:check_status(status_charmed)))n.target=nil
if n:check_status(status_poisoned)do if(n==player)msg.add(n:get_name().." took poison damage")
n:take_dmg(flr(2*(.5+rnd())+.5))end for e=2,4do local e=statuses[e]if n:check_status(e)do if(n.status_timer[e]<=0)n:clear_status(e)
n.status_timer[e]-=1end end n.turn=turn n.followed=false return not n.dead and n:in_frame()and not n:check_status(status_sleeping)end,play_anim=function(e,n,o,d,f,t)tbl_merge(e,{anim=n,anim_frame=n[1],anim_x=o*n[2],anim_y=d*n[2],anim_x1=(f or 0)*n[2],anim_y1=(t or 0)*n[2]})add(creature.anim_queue,e)creature.anim_playing=true end,anim_step=function(n)local d,e,o=smoothstep(n.anim_frame/n.anim[1]),n.anim_x,n.anim_y if n.anim==creature.anims.attack do e,o=n.anim_x1,n.anim_y1 if n.target do if(n.anim_frame==n.anim[1]and n.target==player)flash_frame=2
if(n.anim_frame==n.anim[1]-3)n.target.flash_frame=2
end end n.anim_x=n.anim[2]*d*(e<-.1and-1or e>.1and 1or 0)n.anim_y=n.anim[2]*d*(o<-.1and-1or o>.1and 1or 0)n.anim_frame-=1if n.anim_frame<=0do del(creature.anim_queue,n)if(#creature.anim_queue==0)creature.anim_playing=false
n.anim_x,n.anim_y=0end end,move=function(n,e,o)if not collision(e,o)and e>=0and e<128and o>=0and o<64and(e~=0or o~=0)do if(n.x~=e)n.flipped=n.x>e
n:play_anim(creature.anims.move,n.x-e,n.y-o)tbl_merge(n,{prev_x=n.x,prev_y=n.y,x=e,y=o})return true end return false end,follow=function(e,n)if(in_reach(e,{x=n.prev_x,y=n.prev_y}))e:move(n.prev_x,n.prev_y)else e:move_towards(n)
n.followed=true end,move_towards_and_attack=function(n,e)if(in_reach(n,e))n:attack(e)else n:move_towards(e)
end,move_towards=function(n,e,o)local e,o=o and n.x-e.x or e.x-n.x,o and n.y-e.y or e.y-n.y local f,d=e>0and 1or e<0and-1or 0,o>0and 1or o<0and-1or 0return abs(e)<abs(o)and n:move(n.x,n.y+d)or(n:move(n.x+f,n.y)or n:move(n.x,n.y+d))end,attack=function(n,e)msg.add(n:get_name().." attacked "..e:get_name())if(e:take_dmg(flr(n.ap*(.5+rnd())+.5)))msg.add(n:get_name().." killed "..e:get_name())else e.target=n n.target=e n.target_turn,e.target_turn=turn,turn
n:play_anim(creature.anims.attack,0,0,e.x-n.x,e.y-n.y)end,add_status=function(n,e)n.status_timer[e]=e==status_poisoned and timer_effect_poison or timer_effect if(e==status_scared)n:clear_status(status_charmed|status_sleeping)
if(e==status_charmed or e==status_sleeping)n:clear_status(status_scared)
if(e==status_charmed)n.collision=false n.interactable=false add(player.followers,n)
n.status=n.status|e end,clear_status=function(n,e)n.status=n.status&~e if(e==status_charmed)n.collision=true n.interactable=true del(player.followers,n)
end,check_status=function(e,n)return e.status&n==n end,take_dmg=function(n,e)n:clear_status(status_sleeping)if(e<0)n:clear_status(status_poisoned)
n.blink_delay=frame==0and 2or 1n.attacked=true n.dhp=n.dhp_turn==turn and n.dhp-e or e*-1n.dhp_turn=turn n.hp=min(max(n.hp-e,0),n.max_hp)if(n.hp<=0)n:kill()return true
return false end,kill=function(n)n.dead=true n.collision=false del(player.followers,n)if(n==player)change_state(state_dead)
end})player=creature:new({class="player",parent_class=creature.class,interactable=false,collision=false,name="you",max_hp=20,followers={},look_at=function(n,e)end,action_dir=function(o,d,f)local e=o:move(d,f)for n in all(entity.entities)do if(n.x==d and n.y==f)if n.class==enemy.class and not n:check_status(status_charmed)and not n.dead do o:attack(n)e=true elseif n.class==stairs.class do n:trigger()e=true end
end return e end})companion=creature:new({class="companion",parent_class=creature.class,interact_text="pet",collision=false,ap=1,interact=function(n)msg.add("you petted the "..n:get_name())change_state(state_game)end,do_turn=function(n)if creature.do_turn(n)do if player.target do n:move_towards_and_attack(player.target)else local o=n==companion and player or companion for e in all(player.followers)do if(e~=n and e.turn==turn and not e.followed)o=e break end n:follow(o)end elseif not n:in_frame()do n.x,n.y=player.prev_x,player.prev_y end end})npc=creature:inherit({class="npc",parent_class=creature.class,interact_text="talk",interact=function(n)local n={entity=n,text=split(data_dialogue[n.sprite],"\n"),anim_frame={},pos=1}for e in all(n.text)do add(n.anim_frame,timer_dialog_line+#e*4)end change_state(state_dialogue,n)end})enemy=creature:inherit({class="enemy",parent_class=creature.class,interactable=true,ap=1,max_hp=5,seen_player=0,look_at=function(n,e)if(creature.look_at(n,e)and not n:check_status(status_charmed))e.text="attack"
end,interact=function(n)change_state(state_game)player:attack(n)do_turn()end,do_turn=function(n)if n.status&status_charmed==status_charmed do companion.do_turn(n)elseif creature.do_turn(n)do if(in_sight(n,player))n.seen_player=turn
if(n.seen_player+timer_seen_player>turn)if(n.status&status_scared==status_scared)n:move_towards(player,true)else n:move_towards_and_attack(player)
end end})door=entity:inherit({class="door",parent_class=entity.class,lock=0,new=function(n,e)local n=entity.new(n,e)if(n.collision)mset(n.x,n.y,2)
return n end,look_at=function(e,n)entity.look_at(e,n)if(e.lock==0)n.text=e.collision and"open"or"close"else n.text,n.name="unlock","locked "..n.name if(n.usable)n.key=e.lock n.usable=keys[e.lock]>0and true or false
end,interact=function(n)n.collision=not n.collision n.sprite=n.collision and 82or 81mset(n.x,n.y,n.collision and 2or 1)if(n.lock>0)n.lock=0msg.add"unlocked door"else msg.add((n.collision and"closed"or"opened").." door")
change_state(state_game)end})stairs=entity:inherit({class="stairs",parent_class=entity.class,interactable=false,collision=false,trigger=function(n)local e=nil for n in all(data_floors.stairs)do if(n[1]==player.x and n[2]==player.y)e=n break end local n,o=data_floors.stairs[e[4]],room and room[1]or 0room=data_floors.rooms[n[3]]local o=(room and room[1]or 0)-o cam_x_min,cam_y_min=room and n[1]-player.x or 0,room and n[2]-player.y or 0cam_x_diff,cam_y_diff=n[1]-e[1],n[2]-e[2]player.x,player.y=n[1],n[2]cam_x,cam_y=cam_x+n[1]-e[1],cam_y+n[2]-e[2]msg.add("went "..(o>0and"up"or"down").." stairs")draw.play_fade(change_room,room)end})sign=entity:inherit({class="sign",parent_class=entity.class,interact_text="read",message="...",bg=15,fg=0,new=function(e,n)for e in all(data_signs)do if(e[1]==n.x and e[2]==n.y)n.message=e[3]break
end return entity.new(e,n)end,interact=function(n)change_state(state_read,n)end})chest=entity:inherit({class="chest",parent_class=entity.class,interact_text="open",anim_playing=false,anim_frame=0,anim_this=false,open=false,content={},new=function(o,n)for e in all(data_chests)do if(e.x==n.x and e.y==n.y)n.content={}for e in all(e.content)do add(n.content,tbl_merge_new({sprite=e},data_entities[e]))end return entity.new(o,n)
end end,look_at=function(e,n)entity.look_at(e,n)n.usable=n.usable and not e.open end,interact=function(n)n.open=true n.sprite=12n.anim_frame=45n.anim_this=true chest.anim_playing=true local e={entity=n,anim_frame={}}for n in all(n.content)do add(e.anim_frame,60)msg.add("got "..add_to_inventory(n))end change_state(state_chest,e)end,anim_step=function(n)if(n.anim_frame>0)n.anim_frame-=1
end,item_anim_pos=function(e,n,o)return{x=lerp(n+sin(n*-.5)*.75,pos_to_screen(e).x,o.x),y=lerp(n+cos(n*.9+.1)*.3-.3,pos_to_screen(e).y,o.y)}end,draw=function(n,e)if entity.draw(n,e)and n.anim_this do local o,e=pos_to_screen(n).x,pos_to_screen(n).y if(blink)rectfill(o+1,e+2,o+5,e+3,7)
if(n.anim_frame>=30or n.anim_frame>10and blink)e-=(45-n.anim_frame)*.25clip(o,e,8,5)n:spr(o,e,11)clip()
end end})item=entity:inherit({class="item",parent_class=entity.class,collision=false,interact_text="pick up",interact=function(n)msg.add("picked up "..add_to_inventory(n))n:destroy()change_state(state_game)end})